version: "3"

volumes:
  elastic:
    labels:
      com.screaming_bunny.container: "ElasticSearch"
      com.screaming_bunny.description: "Persistent ElasticSearch Volume"

services:
  core:
    environment:
      ES_HOST: "http://elastic:9200"
      ES_PREFIX: "jazzy ocelot"
    external_links:
      - elastic

#  Elastic export
  elastic:
    hostname: elastic
    image: elasticsearch:7.5.1
    environment:
      node.name: "orc_es01"
      cluster.name: "orc_es-cluster"
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - elastic:/usr/share/elasticsearch/data

  kibana:
    hostname: kibana
    image: kibana:7.5.1
    environment:
      SERVER_NAME: orc_kibana
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - 5601:5601
    external_links:
      - queue
